#!/usr/bin/env node
/**
 * generate-report.js — Builds a consolidated HTML report from the Cucumber JSON outputs
 * produced by the chrome and firefox runs.
 *
 * Looks for:
 *   reports/cucumber-report.json
 *   reports/cucumber-report-chrome.json
 *   reports/cucumber-report-firefox.json
 *
 * Outputs:
 *   reports/html/index.html
 */

'use strict';

const path = require('path');
const fs = require('fs');
const report = require('multiple-cucumber-html-reporter');

const reportsDir = path.resolve('reports');
const jsonDir = reportsDir;
const htmlDir = path.join(reportsDir, 'html');

// Collect all cucumber JSON files in the reports directory
const jsonFiles = fs
  .readdirSync(reportsDir)
  .filter((f) => f.startsWith('cucumber-report') && f.endsWith('.json'));

if (jsonFiles.length === 0) {
  console.warn('[report] No cucumber JSON files found — skipping HTML report.');
  process.exit(0);
}

console.log(`[report] Building HTML report from ${jsonFiles.length} JSON file(s)...`);

report.generate({
  jsonDir,
  reportPath: htmlDir,
  pageTitle: 'Jobrator E2E Report',
  reportName: 'Jobrator BDD Automation Results',
  displayDuration: true,
  durationInMS: false,
  pageFooter: '<div style="text-align:center"><p>Jobrator E2E — generated by multiple-cucumber-html-reporter</p></div>',
  metadata: {
    browser: { name: 'multi', version: 'chromium + firefox' },
    device: 'CI / Local',
    platform: { name: process.platform, version: process.version }
  },
  customData: {
    title: 'Run Info',
    data: [
      { label: 'Project', value: 'Jobrator BDD E2E' },
      { label: 'Site', value: process.env.JOBRATOR_SITE || 'https://jobrator.com/' },
      { label: 'Date', value: new Date().toISOString() },
      { label: 'Standards', value: 'ISTQB + OWASP' }
    ]
  }
});

console.log(`[report] ✅ HTML report → ${path.join(htmlDir, 'index.html')}`);
